name: ci
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        make -j2
        for file in *:*; do
          mv ${i} ${i/:/_}
        done
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          *.torcx.*
