name: ci
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'
  push:
  workflow_dispatch:
    inputs:
      releasename:
        required: true
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        make -j2
        for file in *:*; do
          mv ${file} ${file/:/_}
        done
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          *.torcx.*
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: ci
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Fetch
      uses: actions/download-artifact@v2
      with:
        name: artifacts
    - name: Rename
      run: |
        for file in *.torcx.*; do
          mv ${file} ${file/_/:}
          echo ${file}
        done
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.releasename }}
        tag_name: ${{ github.event.inputs.releasename }}
        files: |
          *.torcx.*
